export default [
  "Fire Ball",
  "Lava Bomb",
  "Flame Shield",
  "Napalm",
  "Rain of Fire",
  "Fire Arrow",
  "Magma Bomb",
  "Flame Wall",
  "Napalm Bomb",
  "Rain of Arrows",
  "Volcano",
  "Summon Flame Dragon",
  "Pebble Shot",
  "Quake",
  "Mud Ball",
  "Rock Slab",
  "Summon Dwarf",
  "Scatter Rock",
  "Disruption",
  "Mega Boulder",
  "Fortress",
  "Summon Rock Golem",
  "Meteor",
  "Fissure",
  "Thunder Shock",
  "Wind Shield",
  "Shock Bomb",
  "Summon Cyclops",
  "Summon Storm Spirit",
  "Chain Lighting",
  "Hurricane",
  "Storm Shield",
  "Conductor Rod",
  "Flight",
  "Storm",
  "Summon Storm Dragon",
  "Ice Ball",
  "Frost Shards",
  "Snowball",
  "Ice Shield",
  "Summon Sylph",
  "Ice Bomb",
  "Frost Arrow",
  "Blizzard",
  "Ice Castle",
  "Summon Frost Giant",
  "Comet",
  "Frost Dragon",
  "Den of Darkness",
  "Drain Bolt",
  "Summon Swarm",
  "Raise Dead",
  "Aura of Decay",
  "Rain of Chaos",
  "Death Bomb",
  "Summon Dark Knight",
  "Summon Wraith",
  "Dark Defenses",
  "Swallowing Pit",
  "Lichdom",
  "Protection Shield",
  "Shining Bolt",
  "Summon Pegasus",
  "Forest Seed",
  "Sphere of Healing",
  "Sky Ray",
  "Rising Star",
  "Summon Paladin",
  "Summon Pixies",
  "Castle of Light",
  "Invulnerability Shield",
  "Shining Power",
  "Thorn Ball",
  "Vine Whip",
  "Entangle",
  "Summon Man-Trap",
  "Summon Elves",
  "Thorn Bomb",
  "Vine Bridge",
  "Vine Bomb",
  "Sanctuary",
  "Flurry",
  "Nature's Wrath",
  "Vine Bloom",
  "Water Ball",
  "Summon Water Trolls",
  "Deluge",
  "Brine Bolt",
  "Summon Brine Goblin",
  "Maelstrom",
  "Hydration",
  "English Summer",
  "Brine Bomb",
  "Rain of Clams",
  "Ocean's Fury",
  "Summon Water Lord",
  "Static Ball",
  "Mechanical Arrow",
  "Recall Device",
  "Clock Tower",
  "Blast From The Past",
  "Static Shield",
  "Cog Fall",
  "Calling Bell",
  "Cuckoo Clock",
  "Clockwork Bomb",
  "Steam Dragon",
  "Redo",
  "Summon Monarchs",
  "Life Dew",
  "Morning Sun",
  "Exploding Pinecone",
  "Summon Snowman",
  "Erosion",
  "Acorn",
  "Breeze",
  "Autumn Leaves",
  "Snow Globe",
  "The Four Seasons",
  "Summon Dryad",
  "Vortex",
  "Whisper Bomb",
  "The ol' Swapparoo",
  "Glide",
  "Air Surge",
  "Magical Barrier",
  "Whiper Arrow",
  "Color Spray",
  "Floating Castle",
  "Summon Phantom",
  "Apparition",
  "Duplication",
  "Bloodlust",
  "Summon Dark Totem",
  "Summon Blood Bank",
  "Barrage of Bones",
  "Flesh Wound",
  "Blood Bath",
  "Resurrection",
  "Retribution",
  "Summon Gargoyle",
  "Blood Clot",
  "Summon Vampire",
  "Infection",
  "Healing Spores",
  "Enchanted Axes",
  "Verdant Javelin",
  "Faerie Jump",
  "Summon Boar",
  "Harmony",
  "Summon Will o' the Wisp",
  "Prickly Barrier",
  "Bear Claw",
  "Summon Tiger",
  "Grove Renewal",
  "Bear Form",
  "Collision Course",
  "Gravity Pulse",
  "Wormhole",
  "Fusion",
  "Summon Drone",
  "Shooting Stars",
  "Dark Matter Bomb",
  "Abduction",
  "MACAIR",
  "Cosmic Horror",
  "Black Hole",
  "Supernova",
  "Pocket Sand",
  "Monolith",
  "Summon Wyrm",
  "Sandbag",
  "Sandy Shores",
  "Bucket of Sand",
  "Pyramid",
  "Sand Trap",
  "Sand Castle",
  "Burning Sands",
  "Sand Storm",
  "Summon Sphinx",
];
